### ISSUE TITLE
Issues/Bugs from 5/28/2020 (Luke)

### ISSUE THREAD

**Issue by PersonGuyGit** [rpgresearch/erpg#1]
Today, I only found issues and(or) bugs with the following NWN::EE Module (p1:f4)

p1f4Module:

All of today's testing was done on a laptop running Windows 10 Home.
The client ran NWN:EE from the Steam Launcher, off of an SSD.

Specs of the testing machine
i7 7th Gen Mobile
GTX 1060 GPU
SSD for boot drive / Hard drive for other files
16GB of DDR4 memory

//

Stephano is able to be killed by the player(s). 
This is triggered by starting combat with Stephano.
This possible logic error, is triggered on 5/5 runs of the module.
(This may possibly be a logic error: I would imagine that players cannot kill Stephano.)

//

During my total of around 5 play sessions on this module, I noticed that a generic NWN loading screen would appear randomly in gameplay. It was nearly instant, similar to a skipped frame or screen tear in a computer game. 
It happened during about 4/5 of the play sessions that I tested.
I was unable to capture the bug with a screenshot, due to the nature of how quickly it happens.

(NOTE: Trevor also noticed the same issue that I did surrounding this "Ghost Loading Screen".)

//

On the dialog action of "Say Nothing", Stephano leaves the area, ignoring the player(s). 
This error is triggered though the intended use, of that dialog option.
It happened on all 5 of the 5 runs tested today.
(I am not sure if that is the desired behavior or not. 
I would imagine that selecting "Say Nothing", would lead the player to an End Dialog option.)

**Comment by MacDugRPG** [comment]
On this same dialogue -- a couple of suggested word changes: "mysterys" to "mysteries" and there's a case where it says him but he's speaking in the 1st person, so maybe change this to "me."

**Comment by tnoye** [comment]
All issues resolved. Thanks for the ticket.
