### ISSUE TITLE
I3 Module

### ISSUE THREAD

**Issue by tnoye** [rpgresearch/erpg#5]
@d-zilla 

## I3 Module

- Unable to converse with sailor. Maybe make a small conversation that he snarls at you or is busy rubbing sticks together? Just a thought. 

- After the sailor exiting and asking "Why did you leave after the shipwreck?", and following with "did ytou happen to see anyone else?", there is no option to return to the ship with Trinculo.

**Comment by d-zilla** [comment]
Regarding the 2nd bullet point, I based it off of the decision tree that was sent to me. I'm assuming that's what we developed on Twine?

**Comment by crossingthesarchasm** [comment]
Yes, that is what we developed in Twine. There should still be that option to return to the ship at the end though, or else we can't progress beyond this branch. Here's the final section of the branch:

3. If character does not return to the boat with Trinculo

[[Ask Trinculo if he saw anyone else]]

Trinculo tells you that he was so frightened by the thought of drowning that he didn't look back at the ship until he was far away. He swears he saw something running toward the woods as he left the ship, though.

[[Return to the ship]]

The two of you return to the ship.
