### ISSUE TITLE
B10-11ModuleFinal 

### ISSUE THREAD

**Issue by MacDugRPG** [rpgresearch/erpg#6]
Nice space to explore, inside and out -- I had the following issues to report:

1. Dialogue: 
   a.  There's a small type-o here: "!."
   b.  King Alonso can be killed. 
   c.  Without the journal, the conversation dies when I ask "What all can you tell me about Prospero?"

2. Journal: maybe out of scope (not a bug), but it would be nice if we could read it -- an easy way to achieve this could be an item description.  

3. Exterior:
  a. I could go in and out, but there's a door on the outside that opens but has no link to travel to -- which confused me initially (I opened this and tried to enter)

**Comment by d-zilla** [comment]
1. Dialogue:
    d. Without the journal, same greeting repeats despite having already talked to him

**Comment by PersonGuyGit** [comment]
I fixed these bugs and issues, after our last meeting on 7/3/2020.
